# -*- coding: utf-8 -*-
"""KMeans on heart data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q4CGuOLbhhnUefqJta1rL49vLvLQ1emb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as pltimport 
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler

heart = pd.read_csv('heart.csv')
y = heart['sex']
heart = heart.drop(columns= ['sex'])

_train, x_test, y_train, y_test = train_test_split(heart,y)

_train.describe()

_train.info()

"""Initial model without any fine tuning

"""

kmeans = KMeans(n_clusters=2)
X = heart.to_numpy()
kmeans.fit(X)

def predict():
  correct = 0
  for i in range(len(X)):
      predict_me = np.array(X[i].astype(float))
      predict_me = predict_me.reshape(-1, len(predict_me))
      prediction = kmeans.predict(predict_me)
      if prediction[0] == y[i]:
          correct += 1

  print(correct/len(X))
predict()

"""Attempt to fine tune


"""

kmeans = kmeans = KMeans(n_clusters=2, max_iter=200, algorithm = 'auto')
kmeans.fit(X)

predict()

"""Standardise data """

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

kmeans.fit(X_scaled)

predict()